name: Build OpenWrt 23.05.5 x86_64 SquashFS Only

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: config  # 将仓库中的配置文件映射到 config 目录

    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
          git gettext libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
          file wget curl

    - name: Clone OpenWrt Source Code
      run: |
        git clone --depth 1 --branch v23.05.5 https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Apply Custom Configuration
      run: |
        # 复制配置文件到正确位置
        cp -rf config/.config openwrt/
        mkdir -p openwrt/files/etc/config
        cp -f config/files/etc/config/network openwrt/files/etc/config/
        
        # 应用配置
        cd openwrt
        make defconfig
        ./scripts/diffconfig.sh > diffconfig
        cat diffconfig

    - name: Build Firmware
      run: |
        cd openwrt
        make -j$(($(nproc) + 1)) V=s 2>&1 | tee build.log
        
        # 验证生成文件
        echo "Generated Images:"
        ls -lh bin/targets/x86/64/*squashfs-combined*.img.gz

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-images
        path: |
          openwrt/bin/targets/x86/64/*squashfs-combined*.img.gz
          openwrt/build.log

    - name: Create GitHub Release
      if: success()
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          openwrt/bin/targets/x86/64/*squashfs-combined*.img.gz
        tag_name: v23.05.5-squashfs
        name: "OpenWrt 23.05.5 (SquashFS Only)"
        body: |
          ### 定制固件特性
          - ​**架构**: x86_64
          - ​**文件系统**: SquashFS (只读)
          - ​**启动支持**: 
            - UEFI (`*-efi.img.gz`)
            - Legacy BIOS (`*-legacy.img.gz`)
          - ​**默认 IP**: 192.168.0.20
          - ​**包含组件**:
            - 中文 LuCI 界面
            - OpenSSH SFTP 服务器
            - nftables 过滤模块
          - ​**编译时间**: ${{ github.run_started_at }}
        draft: false
        prerelease: false
